plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    api 'org.apache.jena:jena-core:5.6.0'
    api 'org.apache.jena:jena-arq:5.6.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
}

test {
    useJUnitPlatform()
}
