plugins {
    id 'java-library'
    id 'maven-publish'
}

dependencies {
    api project(':ccrs-core')
    api 'dev.langchain4j:langchain4j-core:1.10.0'

    implementation 'dev.langchain4j:langchain4j-open-ai:1.10.0'
    implementation 'io.github.cdimascio:dotenv-java:3.0.0'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.11.4'
}

test {
    useJUnitPlatform()
}
