plugins {
    id 'application'
}

group = 'io.github.stefanmhsg.ccrs.examples'
version = '0.1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

dependencies {
    implementation 'io.github.stefanmhsg.ccrs:ccrs-core:0.1.0-SNAPSHOT'
    implementation 'io.github.stefanmhsg.ccrs:ccrs-jacamo:0.1.0-SNAPSHOT'
    implementation 'io.github.stefanmhsg.ccrs:ccrs-hypermedea:0.1.0-SNAPSHOT'
    implementation 'io.github.stefanmhsg.ccrs:ccrs-langchain4j:0.1.0-SNAPSHOT'
    implementation 'io.github.stefanmhsg.ccrs:ccrs-a2a:0.1.0-SNAPSHOT'
}

application {
    mainClass = 'example.CcrsLibraryConsumer'
}
